planning_plugin: ompl_interface/OMPLPlanner
request_adapters: >-
  default_planner_request_adapters/AddTimeOptimalParameterization
  default_planner_request_adapters/FixWorkspaceBounds
  default_planner_request_adapters/FixStartStateBounds
  default_planner_request_adapters/FixStartStateCollision
  default_planner_request_adapters/FixStartStatePathConstraints
response_adapters: >-
  default_planner_response_adapters/AddTimeOptimalParameterization
  default_planner_response_adapters/ValidateSolution
  default_planner_response_adapters/DisplayRandomValidStates

gripper:
  default_planner_config: RRTConnect
  planner_configs:
    - RRTConnect
    - RRT
    - RRTstar
    - TRRT
    - PRM
    - PRMstar
  projection_evaluator: joints(gripper_finger1_joint)
  longest_valid_segment_fraction: 0.005 